<?php

namespace App\Http\Controllers\Voyager;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VoyagerQuestionController extends VoyagerBreadController
{
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function create(Request $request)
    {
//        $view = 'voyager::questions.edit-add';
        return parent::create($request);
//        return view($view);
    }
}
